const shell = require('shelljs');
const exportDir = './dist/resources/app/';
shell.echo(shell.pwd());
shell.echo('making build directory');
shell.mkdir('-p', exportDir, './dist/idTech/');
shell.echo('copying src files into build directory');
shell.cp('-r', './src/*', exportDir);
shell.echo('copying package.json files into build directory');
shell.cp('./package*.json', exportDir);
shell.cp('-Rf', './testData/*', './dist/idTech/');
shell.cp('./*.db', './dist/');